# Generated by Django 3.1.7 on 2021-03-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210320_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
