# Generated by Django 3.1.7 on 2021-03-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_urls_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
