# Generated by Django 3.1.7 on 2021-04-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_urls_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='urls',
            new_name='user',
        ),
    ]
