# Generated by Django 3.1.7 on 2021-06-21 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0010_auto_20210404_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomURLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buat', models.DateTimeField(auto_now_add=True)),
                ('foll', models.PositiveIntegerField(default=0)),
                ('url', models.URLField()),
                ('short_url', models.CharField(blank=True, max_length=15, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Data-Custom URL',
            },
        ),
    ]
