# Generated by Django 3.1.7 on 2021-06-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_customurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='customurls',
            name='domain',
            field=models.CharField(choices=[(1, 'singkat.in'), (2, 'hahahihi.in'), (3, 'pendek.aja')], default='', max_length=30),
        ),
    ]
