# Generated by Django 3.1.7 on 2021-06-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20210621_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='customurls',
            name='long_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customurls',
            name='domain',
            field=models.CharField(choices=[('singkat.in', 'singkat.in'), ('hahahihi.in', 'hahahihi.in'), ('pendek.aja', 'pendek.aja')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='customurls',
            name='url',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
