# Generated by Django 3.1.7 on 2021-06-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210621_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='customurls',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customurls',
            name='short_url',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
