# Generated by Django 3.1.7 on 2021-06-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20210623_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customurls',
            name='domain',
        ),
    ]
