# Generated by Django 3.1.7 on 2021-06-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_customurls_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='short_url',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
