# Generated by Django 3.1.7 on 2021-06-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20210624_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='user_url',
            new_name='user',
        ),
    ]
