# Generated by Django 3.1.7 on 2021-06-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20210626_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurls',
            name='short_url',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
