# Generated by Django 3.1.7 on 2021-06-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20210626_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='customurls',
            name='count_foll',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
