# Generated by Django 3.1.7 on 2021-06-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_customurls_count_foll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurls',
            name='long_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='customurls',
            name='short_url',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
