# Generated by Django 3.1.7 on 2021-06-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20210626_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurls',
            name='short_url',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customurls',
            name='url',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
