# Generated by Django 3.1.7 on 2021-06-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20210627_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurls',
            name='long_url',
            field=models.URLField(),
        ),
    ]
