# Generated by Django 3.1.7 on 2021-06-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_auto_20210629_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customurls',
            name='long_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customurls',
            name='short_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
